name: Win10_LTSC2021_X64

on: 
  workflow_dispatch:
    inputs:
      release:
        description: '上传Release'
        required: true
        type: choice
        options:
          - 'false'
          - 'true'

env:
  Build_VERSION: '19044.7058'
  FILE_NAME: Win10_LTSC2021_X64

jobs:
  Win10_LTSC2021_X64:
    runs-on: windows-latest

    steps:

    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v6

    # 检出Win_ISO_Patching_Scripts仓库
    - name: Checkout repository of Win_ISO_Patching_Scripts
      run: |
        cd ..
        git clone https://github.com/adavak/Win_ISO_Patching_Scripts.git

    # 下载镜像
    - name: download ISO
      shell: pwsh
      run: |
        cd ..
        cd Win_ISO_Patching_Scripts
        
        # 下载镜像
        curl -L -o zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.iso "${{ secrets.MIRROR_LINK_WIN10_LTSC2021 }}"
        ls

    # 集成更新
    - name: Update WinISO
      shell: cmd
      run: |
        :: (可选)替换预设文件W10UI.ini
        copy D:\a\LTSC_Patching\LTSC_Patching\W10UI.ini D:\a\LTSC_Patching\Win_ISO_Patching_Scripts\W10UI.ini /Y

        :: 替换W10UI.cmd
        copy D:\a\LTSC_Patching\LTSC_Patching\W10UI.cmd D:\a\LTSC_Patching\Win_ISO_Patching_Scripts\W10UI.cmd /Y

        :: 切换至Win_ISO_Patching_Scripts根目录 D:\a\LTSC_Patching\Win_ISO_Patching_Scripts
        cd /d D:\a\LTSC_Patching\Win_ISO_Patching_Scripts

        :: 开始集成更新
        Start.cmd

    # 删除母盘
    - name: del MasterISO
      shell: cmd
      run: |
        cd /d D:\a\LTSC_Patching\Win_ISO_Patching_Scripts
        dir
        del /F /S /Q zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.iso
        dir

    # 移动镜像
    - name: Rename
      run: |
        move  ../Win_ISO_Patching_Scripts/*.iso ${{env.FILE_NAME}}.${{env.Build_VERSION}}.iso

    # 上传镜像
    - uses: actions/upload-artifact@v6
      with:
        name: ${{env.FILE_NAME}}.${{env.Build_VERSION}}
        path: ${{env.FILE_NAME}}.${{env.Build_VERSION}}.iso

    # 打包
    - name: Package binaries
      if: ${{ github.event.inputs.release == 'true' }}
      run: |
        7z a -v1950M ${{env.FILE_NAME}}.${{env.Build_VERSION}}.7z ${{env.FILE_NAME}}.${{env.Build_VERSION}}.iso -mx=9

    # 发布镜像
    - name: Release
      if: ${{ github.event.inputs.release == 'true' }}
      uses: softprops/action-gh-release@v2.6.1
      with:
        tag_name: ${{env.FILE_NAME}}.${{env.Build_VERSION}}
        name: ${{env.FILE_NAME}}.${{env.Build_VERSION}}
        files: ${{env.FILE_NAME}}.${{env.Build_VERSION}}.7z*
